export const SPORTS = [
  "Basketball",
  "Soccer",
  "Baseball / Softball",
  "Football (Tackle & Flag)",
  "Volleyball",
  "Swimming / Diving",
  "Track & Field",
  "Cross Country",
  "Tennis",
  "Wrestling",
  "Lacrosse",
  "Gymnastics / Cheer",
  "Hockey (Ice & Field)",
  "Rowing / Crew",
  "Golf",
  "Rugby",
  "Sailing",
  "Water Polo",
  "Martial Arts",
  "Ultimate Frisbee",
] as const;